CLASS zcl_lab_102_storage_4919 DEFINITION INHERITING FROM zcl_lab_101_plant_4919
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_102_storage_4919 IMPLEMENTATION.
ENDCLASS.
