CLASS zcl_lab_lion_4919 DEFINITION INHERITING FROM zcl_lab_104_animal_4919
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    METHODS walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_lion_4919 IMPLEMENTATION.
  METHOD walk.

    rv_walk = 'The lion Walk'.

  ENDMETHOD.

ENDCLASS.
