CLASS zcl_121_airplane_4919 DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    METHODS airplane_type ABSTRACT RETURNING VALUE(rv_airplane_type) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_121_airplane_4919 IMPLEMENTATION.


ENDCLASS.
